import type { Metadata } from 'next'
import { GeistSans } from "geist/font/sans";
import './globals.css'
import { cn } from '@/lib/utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          GeistSans.className,
          "bg-gradient-to-r from-primary to-fuchsia-300 antialiased h-full w-full"
        )}
      >
        {children}</body>
    </html>
  )
}
